ALTER TABLE CPU_Specs
ALTER COLUMN boost_clock_ghz DECIMAL(6,3) NULL;

ALTER TABLE CPU_Specs
ALTER COLUMN graphics NVARCHAR(200) NULL;

ALTER TABLE GPU_Specs
ALTER COLUMN core_clock INT NULL;

ALTER TABLE GPU_Specs
ALTER COLUMN boost_clock INT NULL;

ALTER TABLE GPU_Specs
ALTER COLUMN length INT NULL;

ALTER TABLE Monitor_Specs
ALTER COLUMN refresh_rate INT NULL;

ALTER TABLE Monitor_Specs
ALTER COLUMN response_time INT NULL;

ALTER TABLE Monitor_Specs
ALTER COLUMN panel_type NVARCHAR(50) NULL;

ALTER TABLE Memory_Specs
ALTER COLUMN price_per_gb DECIMAL(10,2) NULL;

ALTER TABLE Memory_Specs
ALTER COLUMN color NVARCHAR(50) NULL;

ALTER TABLE Hard_Drive_Specs
ALTER COLUMN interface NVARCHAR(400) NULL;

ALTER TABLE Hard_Drive_Specs
ALTER COLUMN price_per_gb DECIMAL(10,2) NULL;

ALTER TABLE Hard_Drive_Specs
ALTER COLUMN color NVARCHAR(50) NULL;

ALTER TABLE Power_supply_Specs
ALTER COLUMN efficiency NVARCHAR(50) NULL;

ALTER TABLE Power_supply_Specs
ALTER COLUMN color NVARCHAR(50) NULL;

ALTER TABLE Case_Specs
ALTER COLUMN color NVARCHAR(50) NULL;

ALTER TABLE Case_Specs
ALTER COLUMN side_panel NVARCHAR(100) NULL;

ALTER TABLE Case_Specs
ALTER COLUMN external_volume DECIMAL(4,2) NULL;

ALTER TABLE Motherboard_Specs
ALTER COLUMN color NVARCHAR(50) NULL;